fixes c_rehash call

diff --git a/scripts/fedbiomed_mpc b/scripts/fedbiomed_mpc
--- a/scripts/fedbiomed_mpc
+++ b/scripts/fedbiomed_mpc
@@ -214,10 +214,10 @@ function execute_shamir_server_key(){
   OUTPUT_FILE=$4
   INPUT_FILE=$5
   COMPILE=$6
-#
-#  if ! $(cd "$mpspdz_basedir" && c_rehash); then
-#      error "Certificate error"
-#  fi
+
+  if ! c_rehash "$mpspdz_basedir"/Player-Data; then
+      error "Certificate error"
+  fi
 
   if [ -z "$NUMBER_OF_PARTIES" ] || [ -z "$PARTY_NUMBER" ] || [ -z "$ASSIGNED_IPS" ]; then
     error "There missing arguments. Please make sure that all the arguments are provided.\n\
