replace compose v1 (`docker-compose`) by v2 (`docker compose`)

diff --git a/scripts/fedbiomed_vpn b/scripts/fedbiomed_vpn
--- a/scripts/fedbiomed_vpn
+++ b/scripts/fedbiomed_vpn
@@ -92,13 +92,15 @@ stop           stop and remove all containers
 check_prerequisite() {
     #
     # verify that every needed commands are installed
-    commands=( docker docker-compose )
+    commands=( docker 'docker compose')
 
     ERROR=0
-    for i in ${commands[@]}
+    for i in "${commands[@]}"
     do
-        status=$(which $i)
-        [[ -z "$status" ]] && { echo "** ERROR: command not found: $i"; ERROR=1; }
+        #status=$(which $i)
+        $i >/dev/null 2>&1
+        status=$?
+        [[ "$status" -ne 0 ]] && { echo "** ERROR: command not found: $i"; ERROR=1; }
     done
     [[ $ERROR -eq 1 ]] && { echo "** Please install needed commands before running this script." ; exit 1; }
 }
@@ -204,7 +206,7 @@ containers_remove() {
     cd "$basedir/envs/vpn/docker"
     for i in ${ONLY_CONTAINERS[@]}
     do
-        docker-compose rm -sf $i >/dev/null
+        docker compose rm -sf $i >/dev/null
     done
 }
 
@@ -221,7 +223,7 @@ containers_clean() {
 
     for i in base basenode
     do
-        docker-compose rm -sf $i >/dev/null
+        docker compose rm -sf $i >/dev/null
     done
 
     #
@@ -308,7 +310,7 @@ containers_status() {
     do
         [[ "$i" = "gui" ]] || [[ "$i" = "gui2" ]] && { continue ; } # gui containers do not use wireguard
         echo -n "- pinging VPN server from container $i -> "
-        ping=$(docker-compose exec ${i} ping -n -c 3 -W 1 10.220.0.1 2>/dev/null | cat -v)
+        ping=$(docker compose exec ${i} ping -n -c 3 -W 1 10.220.0.1 2>/dev/null | cat -v)
 
         status=$(echo $ping|grep seq=)
         if [ -z "$status" ]; then
@@ -344,26 +346,26 @@ containers_build() {
         CONTAINER_UID=${CONTAINER_UID:-$(id -u)} CONTAINER_GID=${CONTAINER_GID:-$(id -g)} \
             CONTAINER_USER=${CONTAINER_USER:-$(id -un | sed 's/[^[:alnum:]]/_/g')} \
             CONTAINER_GROUP=${CONTAINER_GROUP:-$(id -gn | sed 's/[^[:alnum:]]/_/g')} \
-            docker-compose build base
+            docker compose build base
     fi
     if [ $BUILD_NODEBASE -eq 1 ]; then
         echo "- building 'basenode' container"
         CONTAINER_UID=${CONTAINER_UID:-$(id -u)} CONTAINER_GID=${CONTAINER_GID:-$(id -g)} \
             CONTAINER_USER=${CONTAINER_USER:-$(id -un | sed 's/[^[:alnum:]]/_/g')} \
             CONTAINER_GROUP=${CONTAINER_GROUP:-$(id -gn | sed 's/[^[:alnum:]]/_/g')} \
-            docker-compose build basenode
+            docker compose build basenode
     fi
 
     for i in ${ONLY_CONTAINERS[@]}
     do
         echo "- stopping '$i' container"
-        docker-compose rm -sf $i >/dev/null
+        docker compose rm -sf $i >/dev/null
         echo "- building '$i' container"
         MPSPDZ_URL=$MPSPDZ_URL MPSPDZ_COMMIT=$MPSPDZ_COMMIT \
             CONTAINER_UID=${CONTAINER_UID:-$(id -u)} CONTAINER_GID=${CONTAINER_GID:-$(id -g)} \
             CONTAINER_USER=${CONTAINER_USER:-$(id -un | sed 's/[^[:alnum:]]/_/g')} \
             CONTAINER_GROUP=${CONTAINER_GROUP:-$(id -gn | sed 's/[^[:alnum:]]/_/g')} \
-            docker-compose build $i
+            docker compose build $i
     done
 }
 
@@ -381,7 +383,7 @@ single_container_configure() {
     IP=$(find_my_ip)
 
     /bin/rm -fr ./vpnserver/run_mounts/config/config_peers/${category}/${container}
-    docker-compose exec vpnserver bash -c -i "python ./vpn/bin/configure_peer.py genconf ${category} ${container}"
+    docker compose exec vpnserver bash -c -i "python ./vpn/bin/configure_peer.py genconf ${category} ${container}"
     sleep 1
 
     /bin/rm -fr ./${container}/run_mounts/config/wireguard    2> /dev/null
@@ -407,7 +409,7 @@ containers_configure() {
     CONTAINER_UID=${CONTAINER_UID:-$(id -u)} CONTAINER_GID=${CONTAINER_GID:-$(id -g)} \
         CONTAINER_USER=${CONTAINER_USER:-$(id -un | sed 's/[^[:alnum:]]/_/g')} \
         CONTAINER_GROUP=${CONTAINER_GROUP:-$(id -gn | sed 's/[^[:alnum:]]/_/g')} \
-        docker-compose up -d vpnserver
+        docker compose up -d vpnserver
 
     for i in ${ONLY_CONTAINERS[@]}
     do
@@ -440,14 +442,14 @@ containers_start() {
 
 
     # Use CONTAINER_UID variable again when starting container(s) because
-    # if image is not build `docker-compose up ` will automatically build it
+    # if image is not build `docker compose up ` will automatically build it
 
     # start vpnserver first
     MPSPDZ_URL=$MPSPDZ_URL MPSPDZ_COMMIT=$MPSPDZ_COMMIT \
         CONTAINER_UID=${CONTAINER_UID:-$(id -u)} CONTAINER_GID=${CONTAINER_GID:-$(id -g)} \
         CONTAINER_USER=${CONTAINER_USER:-$(id -un | sed 's/[^[:alnum:]]/_/g')} \
         CONTAINER_GROUP=${CONTAINER_GROUP:-$(id -gn | sed 's/[^[:alnum:]]/_/g')} \
-        docker-compose up -d vpnserver
+        docker compose up -d vpnserver
 
     # start other container(s)
     for i in ${ONLY_CONTAINERS[@]}
@@ -465,37 +467,37 @@ containers_start() {
         esac
 
         echo "- starting $i container"
-        docker-compose rm -sf $CONTAINER >/dev/null
+        docker compose rm -sf $CONTAINER >/dev/null
         MPSPDZ_URL=$MPSPDZ_URL MPSPDZ_COMMIT=$MPSPDZ_COMMIT \
             CONTAINER_UID=${CONTAINER_UID:-$(id -u)} CONTAINER_GID=${CONTAINER_GID:-$(id -g)} \
             CONTAINER_USER=${CONTAINER_USER:-$(id -un | sed 's/[^[:alnum:]]/_/g')} \
             CONTAINER_GROUP=${CONTAINER_GROUP:-$(id -gn | sed 's/[^[:alnum:]]/_/g')} \
-            docker-compose up -d $CONTAINER
+            docker compose up -d $CONTAINER
 
         case $i in
             mqtt|restful)
-                pubkey=$(docker-compose exec "$i" wg show wg0 public-key | tr -d '\r')
+                pubkey=$(docker compose exec "$i" wg show wg0 public-key | tr -d '\r')
                 # Remove key to avoid protocol error if keys are same
-                docker-compose exec vpnserver python ./vpn/bin/configure_peer.py remove management "$i"
-                docker-compose exec vpnserver python ./vpn/bin/configure_peer.py add management "$i" "$pubkey"
+                docker compose exec vpnserver python ./vpn/bin/configure_peer.py remove management "$i"
+                docker compose exec vpnserver python ./vpn/bin/configure_peer.py add management "$i" "$pubkey"
                 ;;
             researcher)
-                pubkey=$(docker-compose exec researcher wg show wg0 public-key | tr -d '\r')
+                pubkey=$(docker compose exec researcher wg show wg0 public-key | tr -d '\r')
                 # Remove key to avoid protocol error if keys are same
-                docker-compose exec vpnserver python ./vpn/bin/configure_peer.py remove researcher researcher1
-                docker-compose exec vpnserver python ./vpn/bin/configure_peer.py add researcher researcher1 $pubkey
+                docker compose exec vpnserver python ./vpn/bin/configure_peer.py remove researcher researcher1
+                docker compose exec vpnserver python ./vpn/bin/configure_peer.py add researcher researcher1 $pubkey
                 ;;
             node)
-                pubkey=$(docker-compose exec node wg show wg0 public-key | tr -d '\r')
+                pubkey=$(docker compose exec node wg show wg0 public-key | tr -d '\r')
                 # Remove key to avoid protocol error if keys are same
-                docker-compose exec vpnserver python ./vpn/bin/configure_peer.py remove node NODETAG
-                docker-compose exec vpnserver python ./vpn/bin/configure_peer.py add node NODETAG $pubkey
+                docker compose exec vpnserver python ./vpn/bin/configure_peer.py remove node NODETAG
+                docker compose exec vpnserver python ./vpn/bin/configure_peer.py add node NODETAG $pubkey
                 ;;
             node2)
-                pubkey=$(docker-compose exec node2 wg show wg0 public-key | tr -d '\r')
+                pubkey=$(docker compose exec node2 wg show wg0 public-key | tr -d '\r')
                 # Remove key to avoid protocol error if keys are same
-                docker-compose exec vpnserver python ./vpn/bin/configure_peer.py remove node NODE2TAG
-                docker-compose exec vpnserver python ./vpn/bin/configure_peer.py add node NODE2TAG $pubkey
+                docker compose exec vpnserver python ./vpn/bin/configure_peer.py remove node NODE2TAG
+                docker compose exec vpnserver python ./vpn/bin/configure_peer.py add node NODE2TAG $pubkey
                 ;;
             *)
                 ;;
@@ -514,12 +516,12 @@ run() {
     cd "$basedir/envs/vpn/docker"
 
     # find @IP of mqtt and restful inside the VPN
-    status=$(docker-compose ps restful | wc -l)
+    status=$(docker compose ps restful | wc -l)
     [[ $? ]] || {
         echo "** ERROR: restful container not running"
         exit 1
     }
-    restful_IP=$(docker-compose exec restful ip route | tr -d '\r' | grep ^10.220 | awk '{print $NF}')
+    restful_IP=$(docker compose exec restful ip route | tr -d '\r' | grep ^10.220 | awk '{print $NF}')
     echo "- restful IP is: $restful_IP"
     [[ -z "$restful_IP" ]] && {
         echo "** ERROR: cannot find IP address of restful server" ;
@@ -528,12 +530,12 @@ run() {
     }
 
     #
-    status=$(docker-compose ps mqtt | wc -l)
+    status=$(docker compose ps mqtt | wc -l)
     [[ $? ]] || {
         echo "** ERROR: mqtt container not running"
         exit 1
     }
-    mqtt_IP=$(docker-compose exec mqtt ip route | tr -d '\r' | grep ^10.220 | awk '{print $NF}')
+    mqtt_IP=$(docker compose exec mqtt ip route | tr -d '\r' | grep ^10.220 | awk '{print $NF}')
     echo "- mqtt    IP is: $mqtt_IP"
     [[ -z "$mqtt_IP" ]] && {
         echo "** ERROR: cannot find IP address of mqtt server" ;
@@ -544,7 +546,7 @@ run() {
     CMD="export MQTT_BROKER=$mqtt_IP && export MQTT_BROKER_PORT=1883 && export UPLOADS_URL=http://${restful_IP}:8000/upload/ &&
     export UPLOADS_IP=${restful_IP} && export FEDBIOMED_NO_RESET=1 && ./scripts/fedbiomed_run $container ${RUN_ARGS}"
 
-    docker-compose exec -u ${CONTAINER_UID:-$(id -u)} $container bash -c "$CMD"
+    docker compose exec -u ${CONTAINER_UID:-$(id -u)} $container bash -c "$CMD"
 
 
 
