launching gui : better test if `install-only`

diff --git a/scripts/fedbiomed_run b/scripts/fedbiomed_run
--- a/scripts/fedbiomed_run
+++ b/scripts/fedbiomed_run
@@ -44,25 +44,29 @@ function start_gui() {
       CONFIG_FILE="config_node.ini"
       echo -e "${YLW}INFO${NC}: Config file has not been provided, default config 'config_node.ini' will be used for GUI"
     fi
+    if [ -z "${INSTALL_ONLY}" -a ! -f "etc/${CONFIG_FILE}" ] ; then
+        echo "ERROR: 'etc/${CONFIG_FILE}' does not exist in Fed-BioMed root"
+        exit 1
+    fi
 
     # Configure data path
     if [ ! -n "$DATA_PATH" ]; then
       DATA_PATH="data"
       echo -e "${YLW}INFO${NC}: Data path has not been provided. Trying to use \${FEDBIOMED_ROOT}/data dir"
-      if [ ! -d "$basedir/$DATA_PATH" ]; then
+      if [ -z "${INSTALL_ONLY}" -a ! -d "$basedir/$DATA_PATH" ]; then
         echo "ERROR: 'data' folder does not exist in Fed-BioMed root"
         exit 1
       fi
     else
         # If the path is absolute
         if [[ $DATA_PATH == /* ]]; then
-            if [[ ! -d "$DATA_PATH" ]]; then
+            if [[ -z "${INSTALL_ONLY}"  && ! -d "$DATA_PATH" ]]; then
               echo -e "${RED}ERROR${NC}: folder '$DATA_PATH' does not exist. Can not continue.\n"
               exit 1
             fi
         # If the path is relative
         else
-            if [ ! -d "$basedir/$DATA_PATH" ]; then
+            if [ -z "${INSTALL_ONLY}"  -a ! -d "$basedir/$DATA_PATH" ]; then
               echo -e "${RED}ERROR${NC}: folder '$basedir/${DATA_PATH}' does not exist. Can not continue.\n"
               exit 1
             else
