start implementation of launch command, discover @IP of mqtt and restful server

diff --git a/scripts/fedbiomed_vpn b/scripts/fedbiomed_vpn
--- a/scripts/fedbiomed_vpn
+++ b/scripts/fedbiomed_vpn
@@ -36,6 +36,7 @@ Usage: ${0##*/} clean
        ${0##*/} configure
        ${0##*/} start [-g|--gpu]
        ${0##*/} status
+       ${0##*/} launch (node|researcher)
        ${0##*/} stop
 
 manage (local) docker containers with Wireguard VPN support
@@ -58,6 +59,9 @@ start                  start containers
   -g|--gpu             GPU support option (used for node container)
 
 status                 give information on running containers
+
+launch  node           start a node inside node container
+launch  researcher     start a node inside researcher container
 
 stop                   stop  all containers
 "
@@ -337,6 +341,8 @@ containers_configure() {
     echo "** Generating VPN/Wireguards keys"
     cd "$basedir/envs/vpn/docker"
 
+    containers_stop
+
     # replace IP in VPN main config file
     CONFIG="$basedir/envs/vpn/docker/vpnserver/run_mounts/config/config.env"
     IP=$(find_my_ip)
@@ -360,7 +366,7 @@ containers_configure() {
     single_container_configure node1 node node
 
     #
-    containers_stop
+    containers_stop vpnserver
 }
 
 containers_start() {
@@ -412,6 +418,41 @@ containers_start() {
     containers_status
 }
 
+launch() {
+    component=$1
+
+    echo "** Launch $component"
+    cd "$basedir/envs/vpn/docker"
+
+    # find @IP of mqtt and restful inside the VPN
+    status=$(docker-compose ps restful | wc -l)
+    [[ $? ]] || {
+        echo "** ERROR: restful container not running"
+        exit 1
+    }
+    restful_IP=$(docker-compose exec restful ip route | tr -d '\r' | grep ^10.220 | awk '{print $NF}')
+    echo "- restful IP is: $restful_IP"
+    [[ -z "$restful_IP" ]] && {
+        echo "** ERROR: cannot find IP adress of restful server" ;
+        echo "- verify that docker containers are configured"
+        exit 1
+    }
+
+    #
+    status=$(docker-compose ps mqtt | wc -l)
+    [[ $? ]] || {
+        echo "** ERROR: mqtt container not running"
+        exit 1
+    }
+    mqtt_IP=$(docker-compose exec mqtt ip route | tr -d '\r' | grep ^10.220 | awk '{print $NF}')
+    echo "- mqtt    IP is: $mqtt_IP"
+    [[ -z "$mqtt_IP" ]] && {
+        echo "** ERROR: cannot find IP adress of mqtt server" ;
+        echo "- verify that docker containers are configured"
+        exit 1
+    }
+}
+
 # main
 # ----
 
@@ -427,6 +468,8 @@ START=0
 STOP=0
 NODE_NUMBER=1
 GPU=0
+LAUNCH_NODE=0
+LAUNCH_RESEARCHER=0
 
 #
 check_prerequisite
@@ -516,6 +559,20 @@ while (($# > 0)); do
             done
             ;;
 
+        launch)
+            shift
+            while (($# > 0)); do
+                case $1 in
+                    node|n*)        LAUNCH_NODE=1 ;;
+                    researcher|r*)  LAUNCH_RESEARCHER=1 ;;
+                    -h|--help|help) usage ;;
+                    *)              usage "unknown or incompatible arguments" ;;
+                esac
+                shift
+            done
+            [[ $LAUNCH_NODE -eq 0 ]]  && [[ LAUNCH_RESEARCHER  -eq 0 ]] && { usage "launch option need to specify node or researcher" ; }
+            ;;
+
         -h|--help|help) usage ;;
 
         *) usage "unknown or incompatible option: $1";;
@@ -530,11 +587,13 @@ fi
 
 # start doing something usefull
 # -----------------------------
-[[ $CLEAN -eq 1 ]]     && { containers_clean; }
-[[ $BUILD -eq 1 ]]     && { containers_build; }
-[[ $CONFIGURE -eq 1 ]] && { containers_configure; }
-[[ $START -eq 1 ]]     && { containers_start; }
-[[ $STOP -eq 1 ]]      && { containers_stop; }
-[[ $STATUS -eq 1 ]]    && { containers_status; }
+[[ $CLEAN -eq 1 ]]             && { containers_clean; }
+[[ $BUILD -eq 1 ]]             && { containers_build; }
+[[ $CONFIGURE -eq 1 ]]         && { containers_configure; }
+[[ $START -eq 1 ]]             && { containers_start; }
+[[ $STOP -eq 1 ]]              && { containers_stop; }
+[[ $STATUS -eq 1 ]]            && { containers_status; }
+[[ $LAUNCH_NODE -eq 1 ]]       && { launch node; }
+[[ $LAUNCH_RESEARCHER -eq 1 ]] && { launch researcher; }
 
 exit 0
