add support for non-localhost for joining network

diff --git a/scripts/fedbiomed_run b/scripts/fedbiomed_run
--- a/scripts/fedbiomed_run
+++ b/scripts/fedbiomed_run
@@ -35,19 +35,39 @@ case $1 in
 
     node)
 
-        # deal with alternative config file
-        if [ $# -ge 4 -a "${@:$#-1:1}" = 'config' ]
+        while true ; do
+            case $2 in
+                # handle optional parameters : config file, network ip
+                config)
+                    if [ $# -lt 3 ] ; then
+                        echo "ERROR: missing config file name"
+                        exit 1
+                    fi
+                    CONFIG_FILE=$3
+                    shift
+                    shift
+                ;;
+                network_ip)
+                    if [ $# -lt 3 ] ; then
+                        echo "ERROR: missing network ip"
+                        exit 1
+                    fi
+                    NETWORK_IP=$3
+                    shift
+                    shift
+                ;;
+                *)
+                    break
+                ;;
+            esac
+        done
+        
+        # pass remaining params to launched script
+        if [ $# -ge 2 ]
         then
-            export CONFIG_FILE=${@:$#}
-            export PARAMS=${@:3:$#-4}
+            export PARAMS=${@:3:$#-2}
         else
-            unset CONFIG_FILE
-            if [ $# -ge 3 ]
-            then
-                export PARAMS=${@:3:$#-2}
-            else
-                export PARAMS=
-            fi
+            export PARAMS=
         fi
 
         # TODO : better test with python module loading attempt and try/except
@@ -56,27 +76,27 @@ case $1 in
             case $2 in
 
                 list|--list|-l)
-                    source ./scripts/fedbiomed_environment node
+                    source ./scripts/fedbiomed_environment node $NETWORK_IP
                     python -m fedbiomed.node.cli --list $PARAMS
                     ;;
 
                 del|delete|--del|--delete|-d)
-                    source ./scripts/fedbiomed_environment node
+                    source ./scripts/fedbiomed_environment node $NETWORK_IP
                     python -m fedbiomed.node.cli --delete $PARAMS
                     ;;
 
-                --delete-mnist|-dm)
-                    source ./scripts/fedbiomed_environment node
+                delete-mnist|--delete-mnist|-dm)
+                    source ./scripts/fedbiomed_environment node $NETWORK_IP
                     python -m fedbiomed.node.cli --delete-mnist $PARAMS
                     ;;
 
                 add|--add|-a)
-                    source ./scripts/fedbiomed_environment node
+                    source ./scripts/fedbiomed_environment node $NETWORK_IP
                     python -m fedbiomed.node.cli --add $PARAMS
                     ;;
 
-                --add-mnist|-am)
-                    source ./scripts/fedbiomed_environment node
+                add-mnist|--add-mnist|-am)
+                    source ./scripts/fedbiomed_environment node $NETWORK_IP
                     python -m fedbiomed.node.cli --add-mnist $PARAMS
                     ;;
 
@@ -84,7 +104,7 @@ case $1 in
                     #export MQTT_BROKER=localhost
                     #export MQTT_BROKER_PORT=1883
                     #export UPLOADS_URL='http://localhost:8844/upload/'
-                    source ./scripts/fedbiomed_environment node
+                    source ./scripts/fedbiomed_environment node $NETWORK_IP
                     python -m fedbiomed.node.cli --start $PARAMS
                     ;;
                 *)
@@ -101,7 +121,25 @@ case $1 in
         #export MQTT_BROKER=localhost
         #export MQTT_BROKER_PORT=1883
         #export UPLOADS_URL='http://localhost:8844/upload/'
-        source ./scripts/fedbiomed_environment researcher
+
+        while true ; do
+            case $2 in
+                network_ip)
+                    if [ $# -lt 3 ] ; then
+                        echo "ERROR: missing network ip"
+                        exit 1
+                    fi
+                    NETWORK_IP=$3
+                    shift
+                    shift
+                ;;
+                *)
+                    break
+                ;;
+            esac
+        done
+
+        source ./scripts/fedbiomed_environment researcher $NETWORK_IP
         cd notebooks
         jupyter notebook
         ;;
@@ -109,11 +147,10 @@ case $1 in
     help|-h|--help)
         cat <<EOF
 usage: fedbiomed_run network
-       fedbiomed_run researcher
-       fedbiomed_run node       add    (config_name.ini)
-       fedbiomed_run node       start  (config_name.ini)
-       fedbiomed_run node       delete (config_name.ini)
-       fedbiomed_run node       list   (config_name.ini)
+       fedbiomed_run researcher (network_ip NETWORK_IP))
+       fedbiomed_run node (config CONFIG_NAME | network_ip NETWORK_IP)
+                         [start | add | list | delete | add-mnist | delete-mnist] PARAMS
+
 
 Runs the fedbiomed components after properly initializing the environments.
 The component name is mandatory.
@@ -122,12 +159,20 @@ network   : run the necessary docker containers (in development mode)
 
 researcher: launch a researcher notebook
 
-node      : a second arguement is mandatory
-            start : launch a new node
-            add/list/delete deals with dataset
+            an optional NETWORK_IP can be used to join the network component instead of
+                the default localhost
 
-            if a config_name.ini file is given as third argeument,
-            it will be used instead of the default one (config.ini)
+node      : a second arguement is mandatory
+            - start : launch a new node
+            - add/list/delete deals with dataset
+            - add-mnist PATH_TO_DATASET directly adds a mnist dataset
+            - delete-mnist directly removes a mnist dataset
+
+            an optional config file CONFIG_NAME can be given it will be used instead of the default one (config.ini)
+
+            an optional NETWORK_IP can be used to join the network component instead of
+                the default localhost
+
 EOF
         ;;
 
