changed arg parsing

diff --git a/scripts/fedbiomed_vpn b/scripts/fedbiomed_vpn
--- a/scripts/fedbiomed_vpn
+++ b/scripts/fedbiomed_vpn
@@ -14,32 +14,39 @@
 
 
 # all functions
+# -------------
 usage() {
     #
     # print usage
     #
     echo "\
-Usage: ${0##*/} [-b|--build] [-c|--clean] [-g|--generate-keys]
-       ${0##*/} [-s|--server] [-m|--model-approval]
-       ${0##*/} [-n|--node]   [-m|--model-approval]
+Usage: ${0##*/} build  [-c|--clean] [-g|--generate-keys]
+       ${0##*/} server [-m|--model-approval] start|stop
+       ${0##*/} node   [-m|--model-approval] start|stop
 
 Build/configure/run docker containers for VPN support
 ( build / node / server flags are incompatibles )
 
 
- -b|--build          build all containers
+ build                    build all containers
 
      Optional with --build:
 
      -c|--clean           clean environments first
      -g|--generate_keys   generate new keys for components
 
- -s|--server        start local server's dockers (already built)
- -n|--node          start a local node's docker (already built_
+ server                   start/stop local server's dockers (already built)
+ node                     start/stop a local node's docker  (already built)
+
+     Required with --node/--server:
+
+     start                start the component
+     stop                 stop  the component
 
      Optional with --node/--server:
 
      -m|--model-approval  enforce model approval in config files
+
 "
 }
 
@@ -94,6 +101,12 @@ find_my_ip() {
         [[ ! -z "$IP" ]] && { echo $IP ; return ; }
     done
 
+    case $IP in
+        127.*)
+            echo "WARNING: vpnserver will use the localhost IP adress."
+            echo "         vpnserver may not work properly"
+        ;;
+    esac
     # just in case (never happends but I am paranoid)
     return "127.0.0.1"
 }
@@ -113,12 +126,6 @@ container_build() {
     echo "- building vpnserver"
     CONTAINER_UID=$(id -u) CONTAINER_GID=$(id -g) CONTAINER_USER=$(id -un) CONTAINER_GROUP=$(id -gn) docker-compose build vpnserver
 
-    # substitute @IP in config file
-    CONFIG="$basedir/envs/vpn/docker/vpnserver/run_mounts/config/config.env"
-    IP=$(find_my_ip)
-    git checkout $CONFIG
-    sed -i -e "s:replace_with.myserver.mydomain:$IP:" $CONFIG
-
 }
 
 keys_generate() {
@@ -130,10 +137,22 @@ start_node() {
 }
 
 start_servers() {
-    echo "STARTING servers"
+    echo "STARTING server"
+
+    cd "$basedir/envs/vpn/docker"
+
+    # substitute @IP in config file
+    CONFIG="$basedir/envs/vpn/docker/vpnserver/run_mounts/config/config.env"
+    IP=$(find_my_ip)
+
+    git checkout $CONFIG
+    sed -i -XXX "s:replace_with.myserver.mydomain:$IP:" $CONFIG && /bin/rm ${CONFIG}-XXX
+
+    docker-compose up -d vpnserver
 }
 
-### main
+# main
+# ----
 
 # detect topdir
 basedir=$(cd $(dirname $0)/.. || exit ; pwd)
@@ -146,6 +165,10 @@ GENERATE=0
 NODE=0
 SERVER=0
 APPROVAL=0
+START=0
+STOP=0
+
+ERROR=0
 
 # must provide at least an option
 if [ $# -eq 0 ]; then
@@ -159,92 +182,85 @@ fi
 while (($# > 0)); do
     case $1 in
 
-        -b|--build)
+        build)
             BUILD=1
+            shift
+            while (($# > 0)); do
+                case $1 in
+                    -c|--clean)         CLEAN=1 ;;
+                    -g|--generate_keys) GENERATE=1 ;;
+                    -h|--help)          usage ; exit 0 ;;
+                    *)
+                        echo "unknown or incompatible arguments"
+                        usage
+                        exit 1
+                        ;;
+                esac
+                shift
+            done
             ;;
 
-        -c|--clean)
-            CLEAN=1
-            ;;
+        node|server)
 
-        -g|--generate_keys)
-            GENERATE=1
-            ;;
+            if [ $1 = "node" ]; then
+                NODE=1
+            fi
+            if [ $1 = "server" ]; then
+                SERVER=1
+            fi
 
-        -h|--help)
-            usage
-            exit 0
+            shift
+            while (($# > 0)); do
+                case $1 in
+                start)
+                    START=1
+                    ;;
+                stop)
+                    STOP=1
+                    ;;
+                -m|--model-approval)
+                    APPROVAL=1
+                    ;;
+                *)
+                    echo "unknown or incompatible option: $1"
+                    usage
+                    exit 1
+                    ;;
+                esac
+                shift
+            done
             ;;
-
-        -m|--model-approval)
-            APPROVAL=1
-            ;;
-
-        -n|--node)
-            NODE=1
-            ;;
-
-        -s|--server)
-            SERVER=1
-            ;;
-
         *)
-            echo "unknown option: $1"
-
+            echo "unknown or incompatible option: $1"
             usage
             exit 1
             ;;
-
     esac
     shift
 done
 
-
-# check arguments coherence
-ERROR=0
-if [ $NODE -eq 1 ]; then
-    if [ $SERVER -eq 1 ]; then
-        echo "-n and -s flags are not compatible"
-        ERROR=1
-    fi
-    if [ $BUILD -eq 1 ]; then
-        echo "-n and -b flags are not compatible"
-        ERROR=1
-    fi
-    if [ $CLEAN -eq 1 ]; then
-        echo "-n and -c flags are not compatible"
-        ERROR=1
-    fi
-    if [ $GENERATE -eq 1 ]; then
-        echo "-n and -g flags are not compatible"
-        ERROR=1
+# concatenate start/stop into ACTION
+ACTION=""
+if [ $STOP -eq 1 ]; then
+    if [ $START -eq 0 ]; then
+        ACTION=stop
+    else
+        echo "ERROR: do I stay or do I go ? (start and stop both requested)"
+        usage
+        exit 1
     fi
 fi
-if [ $SERVER -eq 1 ]; then
-    if [ $NODE -eq 1 ]; then
-        echo "-s and -n flags are not compatible"
-        ERROR=1
-    fi
-    if [ $BUILD -eq 1 ]; then
-        echo "-s and -b flags are not compatible"
-        ERROR=1
-    fi
-    if [ $CLEAN -eq 1 ]; then
-        echo "-s and -c flags are not compatible"
-        ERROR=1
-    fi
-    if [ $GENERATE -eq 1 ]; then
-        echo "-s and -g flags are not compatible"
-        ERROR=1
-    fi
+if [ $START -eq 1 ]; then
+    ACTION=start
 fi
-
-if [ $ERROR -eq 1 ]; then
+if [ -z $ACTION ]; then
+    echo "ERROR: must provide start or stop"
     usage
     exit 1
 fi
 
 # start doing something usefull
+# -----------------------------
 if [ $CLEAN -eq 1 ]; then
     container_clean
 fi
