Allows define path for for input and output files

diff --git a/scripts/fedbiomed_mpc b/scripts/fedbiomed_mpc
--- a/scripts/fedbiomed_mpc
+++ b/scripts/fedbiomed_mpc
@@ -106,6 +106,29 @@ EOF
 
 }
 
+function error(){
+    echo -e "\n${RED}ERROR:${NC}"
+    echo -e "${BOLD}$1${NC}"
+    exit 1
+}
+
+function absolute_path(){
+  path=$1
+  for=$2
+  directory=${path%/*}
+
+  # Check directory is existing
+  if [ ! -d "$directory" ]; then
+    error "Directory is not existing for '$for': $directory/. \n\
+    \rIf you are using relative path please make sure the format respect where the script is executed"
+  fi
+
+  # Retrieve absolute path
+  absolute="$(cd "$(dirname -- "$path")" >/dev/null; pwd -P)/$(basename -- "$path")"
+  echo "$absolute"
+}
+
+
 # Compile action ------------------------------------------------------------------------------------------------
 function compile(){
 
@@ -162,18 +185,13 @@ function execute_protocol(){
     exit 1
   fi
 
-
   echo -e "${GRN}Executing protocol '$PROTOCOL'...${NC}"
   echo -e "${BOLD}Press CTRL+C to stop${NC}"
   exec_out=$(cd "$mpspdz_basedir" && ./"$PROTOCOL".x $EXTRA_ARGS)
 
   if [ ! $? -eq 0 ]; then
-    echo -e "\n${RED}ERROR:${NC}"
-    echo -e "${BOLD}Error while executing protocol '$PROTOCOL'. Please check the logs above${NC}\n"
-    exit 1
+    error "Error while executing protocol '$PROTOCOL'. Please check the logs above\n"
   fi
-
-
 }
 
 
@@ -183,48 +201,87 @@ function execute_shamir_server_key(){
   PARTY_NUMBER=$2
   ASSIGNED_IPS=$3
   OUTPUT_FILE=$4
-  COMPILE=$5
+  INPUT_FILE=$5
+  COMPILE=$6
 
-  if [ -z "$NUMBER_OF_PARTIES" ] || [ -z "$PARTY_NUMBER" ] || [ -z "$ASSIGNED_IPS" ] || [ -z "$OUTPUT_FILE" ]; then
-    echo -e "\n${RED}ERROR:${NC}"
-    echo -e "${BOLD}There missing arguments. Please make sure that all the arguments are provided.${NC}\n\
+  if [ -z "$NUMBER_OF_PARTIES" ] || [ -z "$PARTY_NUMBER" ] || [ -z "$ASSIGNED_IPS" ]; then
+    error "There missing arguments. Please make sure that all the arguments are provided.\n\
             \rSee 'fedbiomed_mpc shamir-server-key --help'"
-    exit 1
   fi
 
-
-  if [ -n "$COMPILE" ]; then
-    if ! "$basedir"/scripts/fedbiomed_mpc compile --script server_key -N "$NUMBER_OF_PARTIES"; then
-      echo -e "\n${RED}ERROR:${NC}"
-      echo -e "${BOLD}Error while executing protocol '$PROTOCOL'. Please check the logs above${NC}\n"
+  # Check output file if party number is 0 (server) -------------------------------------------------------------------
+  if [ "$PARTY_NUMBER" -eq 0 ]; then
+    if [ -z "$OUTPUT_FILE" ]; then
+      error "Party 0 should have an output file specified with the option -of | --output-file"
+    elif ! OUTPUT_FILE=$(absolute_path "$OUTPUT_FILE" "--output-file | -of option" ); then
+      echo  "$OUTPUT_FILE"
+      exit 1
+    fi
+  # Check input file if party number is different than 0 --------------------------------------------------------------
+  else
+    if [ -z "$INPUT_FILE" ]; then
+      error "Parties different than '0 (server)' should have an output file specified with the option -if | --input-file"
+    elif ! INPUT_FILE=$(absolute_path "$INPUT_FILE" "--input-file | -if option" ); then
+      echo  "$INPUT_FILE"
       exit 1
     fi
   fi
+
+  # Check file for ip addresses is existing ---------------------------------------------------------------------------
+  if [ ! -f "$ASSIGNED_IPS" ]; then
+    error "The file for assigned ip addresses not found.If the given path is a relative path please make the path \n\
+    \rrespects where ths command/script is executed"
+  else
+    ASSIGNED_IPS="$(cd "$(dirname -- "$ASSIGNED_IPS")" >/dev/null; pwd -P)/$(basename -- "$ASSIGNED_IPS")"
+  fi
+
+  # Compile server key MPC file --------------------------------------------------------------------------------------
+  if [ -n "$COMPILE" ]; then
+    if ! "$basedir"/scripts/fedbiomed_mpc compile --script server_key -N "$NUMBER_OF_PARTIES"; then
+      error "Error while executing protocol '$PROTOCOL'. Please check the logs above"
+    fi
+  fi
+
 
   # Generate the key-share
   if [ ! "$PARTY_NUMBER" -eq 0 ]; then
     echo -e "${GRN}Generating key share for party $PARTY_NUMBER ${NC}"
-    if ! python "$basedir"/MP-SPDZ/generate_sk.py --n_len 2048 > "$mpspdz_basedir"/Player-Data/Server-Key-Input-P"$PARTY_NUMBER"-0; then
-      echo -e "\n${RED}ERROR:${NC}"
-      echo -e "${BOLD}Error while generating key share.${NC}\n"
-      exit 1
+    if ! python "$basedir"/MP-SPDZ/generate_sk.py --n_len 2048 > "$INPUT_FILE"-P"$PARTY_NUMBER"-0; then
+      error "Error while generating key share."
     fi
-    echo -e "${BOLD}Done! Key generated in $mpspdz_basedir/Player-Data/Server-Key-Input-P$PARTY_NUMBER-0${NC}"
+    echo -e "${BOLD}Done! Key generated in $INPUT_FILE-P$PARTY_NUMBER-0${NC}"
   fi
   echo -e "\n${YLW}Execution info:${NC}"
   echo -e "${YLW}---------------------------------------${NC}"
   echo -e "${BOLD}Party no          :${NC} $PARTY_NUMBER"
   echo -e "${BOLD}Number of parties :${NC} $NUMBER_OF_PARTIES"
   echo -e "${BOLD}Assigned IPs      :${NC} $ASSIGNED_IPS"
-  echo -e "${BOLD}Output file       :${NC} $OUTPUT_FILE"
-  echo -e "${BOLD}Input file        :${NC} $mpspdz_basedir/Player-Data/Server-Key-Input-P$PARTY_NUMBER-0 \n"
 
-  "$basedir"/scripts/fedbiomed_mpc exec --protocol shamir-party "$PARTY_NUMBER" \
+  # If party is 0 (server)
+  if [ "$PARTY_NUMBER" -eq 0 ]; then
+      echo -e "${BOLD}Output file       :${NC} $OUTPUT_FILE-P$PARTY_NUMBER-0"
+  # If party is 1
+  else
+      echo -e "${BOLD}Input file        :${NC} $INPUT_FILE-P$PARTY_NUMBER-0 \n"
+  fi
+
+  # If party is not zero they will have input files
+  if [ ! "$PARTY_NUMBER" -eq 0 ]; then
+      "$basedir"/scripts/fedbiomed_mpc exec --protocol shamir-party "$PARTY_NUMBER" \
         -ip "$ASSIGNED_IPS" \
-        -IF "$mpspdz_basedir"/Player-Data/Server-Key-Input \
-        -OF "$OUTPUT_FILE" \
+        -IF "$basedir"/Server-Key-Input \
         server_key \
         -N "$NUMBER_OF_PARTIES"
+
+  # If party is zero it should have input file
+  else
+      "$basedir"/scripts/fedbiomed_mpc exec --protocol shamir-party "$PARTY_NUMBER" \
+          -ip "$ASSIGNED_IPS" \
+          -OF "$basedir"/"$OUTPUT_FILE" \
+          server_key \
+          -N "$NUMBER_OF_PARTIES"
+  fi
+
 
 }
 
@@ -316,6 +373,11 @@ case $1 in
           shift # past argument
           shift # past value
           ;;
+        -if|--input-file)
+          INPUT_FILE="$3"
+          shift
+          shift
+        ;;
         -c|--compile)
           COMPILE=1
           shift # past argument
@@ -337,7 +399,7 @@ case $1 in
       esac
     done
 
-    execute_shamir_server_key "$NUMBER_OF_PARTIES" "$PARTY_NUMBER" "$ASSIGNED_IPS" "$OUTPUT_FILE" "$COMPILE"
+    execute_shamir_server_key "$NUMBER_OF_PARTIES" "$PARTY_NUMBER" "$ASSIGNED_IPS" "$OUTPUT_FILE" "$INPUT_FILE" "$COMPILE"
   ;;
   -h|--help)
     help main
