Adds secure aggregation helpers for e2e tests - New e2e test file for secure aggregation - Helper function to configure secagg - Helper function to register certificates automatically. - Fix MP-SPDZ installation issue for Mac - Disable env remove for end to end test

diff --git a/scripts/fedbiomed_configure_secagg b/scripts/fedbiomed_configure_secagg
--- a/scripts/fedbiomed_configure_secagg
+++ b/scripts/fedbiomed_configure_secagg
@@ -57,7 +57,7 @@ if [ "$2" != "clone" ] ; then
   echo -e "${BOLD}Updating MP-SPDZ submodule${NC}\n"
   git submodule update --init modules/MP-SPDZ
 else
-  # Clone repository and point to correct commit 
+  # Clone repository and point to correct commit
   # Should be used only in case there is no submodule defined for MP-SPDZ
   if [ -n "$MPSPDZ_URL" -a -z "$(ls -A $mpspdz_basedir)" ] ; then
     echo -e "${BOLD}Cloning MP-SPDZ repository${NC}\n"
@@ -73,7 +73,7 @@ else
     if ! git checkout "$MPSPDZ_COMMIT" ; then
       echo -e "${RED}ERROR:${NC}"
       echo -e "${BOLD} Please make sure that MP-SPDZ is already cloned and '$MPSPDZ_COMMIT' is an existing commit."
-      exit 1    
+      exit 1
     fi
   fi
 fi
@@ -126,7 +126,12 @@ configure_darwin() {
     exit 1
   fi
 
-  echo -e "\n${YLW}--------------------------------Building from source distribution---------------------------${NC}"
+  if ! cd $mpspdz_basedir && git submodule update --init deps/simde; then
+	echo -e "${RED}ERROR:${NC}"
+    echo -e "${BOLD}Can not build MP-SPDZ. Can not add simde submodule"
+  fi
+
+  echo -e "\n${YLW}------------------Building from source distribution---------------------------${NC}"
 
   echo -e "${GRN}\nRunning make clean ...${NC}"
   if ! make -C "$mpspdz_basedir" clean; then
