run_integration_test cleans to temporary files

diff --git a/scripts/run_integration_test b/scripts/run_integration_test
--- a/scripts/run_integration_test
+++ b/scripts/run_integration_test
@@ -101,12 +101,11 @@ script_executor() {
             convert=$(jupyter nbconvert --output-dir=/tmp --output=$output --to script $script 2> /dev/null)
             if [ $? == 0 ]
             then
-                FILES_TO_CLEAN+=" $output"
                 # conversion did well
                 echo "ipython /tmp/$output.py"
             else
                 # must quit
-                echo "$script: CANNOT RUN THIS SCRIPT"
+                echo "CANNOT RUN THIS SCRIPT: $script"
                 return -1
             fi
             ;;
@@ -143,7 +142,8 @@ cleaning() {
     # clean files
     if [ ! -z "$FILES_TO_CLEAN" ]
     then
-        /bin/rm -fr $FILES_TO_CLEAN
+        echo "** INFO: cleaning file(s): $FILES_TO_CLEAN"
+        /bin/rm -f $FILES_TO_CLEAN
     fi
 
     # clean running node processes
@@ -152,7 +152,6 @@ cleaning() {
         echo "** INFO: no node process to kill"
     else
         echo "** INFO: killing node processes: $all_pids"
-        /usr/local/bin/pstree $npid
         kill -15 $all_pids
         sleep 3
         kill -9 $all_pids 2> /dev/null
@@ -189,8 +188,10 @@ trap cleaning_trap INT
 # locate the topdir of the distribution
 # WARNING: providing a relative dataset.json file containing a relative 'path' value  will not work
 # TODO: fix this
-basedir=$(cd $(dirname $0)/.. || exit -1 ; pwd)
-cd $basedir || exit -1
+basedir=$(cd $(dirname $0)/.. || exit 1 ; pwd)
+
+# deal with arguments being relative files (done later)
+CURRENT_DIR=$(pwd)
 
 # prerequisite: OS specific commands
 case $(uname) in
@@ -246,12 +247,32 @@ done
 [[ $SCRIPT ]] || bad_usage "providing a script is mandatory"
 [[ $DATASET ]] || bad_usage "providing a dataset json description is mandatory"
 
+# transform relative filenames to absolute filenames
+case $SCRIPT in
+    /* ) ;; # nothing to do
+    *)
+        SCRIPT="${CURRENT_DIR}/${SCRIPT}"
+        ;;
+esac
+case $DATASET in
+    /* ) ;; # nothing to do
+    *)
+        DATASET="${CURRENT_DIR}/${DATASET}"
+        ;;
+esac
+
 # is script ok ?
 CMD_TO_RUN=$(script_executor $SCRIPT)
-if [  $? == 0 ]
+
+# if CMD_TO_RUN is an ipython script, we should clean the file at the end
+case $CMD_TO_RUN in
+    ipython*)
+        FILES_TO_CLEAN+="${CMD_TO_RUN##* }"
+    ;;
+esac
+
+if [  ! $? == 0 ]
 then
-    echo $CMD_TO_RUN
-else
     echo "ERROR: I do not know how to launch: $SCRIPT"
     echo "       I need a python/notebook or at least an executable"
     exit 1
@@ -266,7 +287,6 @@ then
 fi
 
 ##### try to run this thing....
-
 
 # launch network
 echo "** INFO: launching fedbiomed network"
